### ISSUE TITLE
npm start gives error : Unhandled rejection TypeError: Cannot read property 'table' of null

### ISSUE THREAD

**Issue by nikitph** [casoetan/react-horizon#2]
``` sh
Unhandled rejection TypeError: Cannot read property 'table' of null
    at /Users/Omkareshwar/react-horizon/source/server/auto/createTodos.js:27:13
    at tryCatcher (/Users/Omkareshwar/react-horizon/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Omkareshwar/react-horizon/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/Omkareshwar/react-horizon/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/Omkareshwar/react-horizon/node_modules/bluebird/js/release/promise.js:612:10)
```

i think horizon's version 2 might b the problem

**Comment by casoetan** [comment]
@nikitph thats right.

Can you create a pull request to fix this?

**Comment by nikitph** [comment]
I unfortunately haven't been able to make it work yet. Will put in a
request if i have a fix

**Comment by casoetan** [comment]
Fixed in 0.4.0 by this commit https://github.com/casoetan/react-horizon/commit/5d715d00826977c2b6f9791d3320e8ba8b1f5835.

You will have to migrate your existing db, or delete it and let the app recreate it.

**Comment by casoetan** [comment]
@nikitph do you mind being a collaborator on this project?

**Comment by nikitph** [comment]
i m actually in the middle of a job search... so dont know how much i would be able to contribute. if you are looking for help on time sensitive stuff i am probably not best suited.

**Comment by nikitph** [comment]
hmm... we get this in the new build. i blew away the entire rethinkdb instance but this still happens

Unhandled rejection ReqlOpFailedError: Database `react_horizon_internal` does not exist in:
r.table("collections").get("todos")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```
at Connection._processResponse (/Users/Omkareshwar/Documents/react-horizon/node_modules/rethinkdbdash/lib/connection.js:382:15)
at Socket.<anonymous> (/Users/Omkareshwar/Documents/react-horizon/node_modules/rethinkdbdash/lib/connection.js:201:14)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)
at readableAddChunk (_stream_readable.js:172:18)
at Socket.Readable.push (_stream_readable.js:130:10)
at TCP.onread (net.js:535:20)
```

**Comment by casoetan** [comment]
Fixed. https://github.com/casoetan/react-horizon/commit/15524ea40d6fcde1a6540c827bb67cc574ecc7dc.

Part of the update to horizon.io 2

**Comment by casoetan** [comment]
Does this fix your issue @nikitph?

**Comment by nikitph** [comment]
yeah.. i think this is it.
